### ISSUE TITLE
Dependency and compatibility issues installing BioTools

### ISSUE THREAD

**Issue by hodgensc** [BioJulia/BioTools.jl#12]
I mentioned this issue on the Julia slack and @kescobo requested I start an issue for it.

I'm trying to add BioTools (for the BLAST wrapper) and running into a compatibility issue when attempting to add it using the Package manager.

## Expected Behavior
The package is installed.

## Current Behavior
I get the following output:
```
pkg> add BioTools
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package BioSequences [7e6ae17a]:
 BioSequences [7e6ae17a] log:
 ├─possible versions are: 1.0.0-3.1.6 or uninstalled
 ├─restricted by compatibility requirements with BioTools [fa51a905] to versions: 1.0.0-1.1.0
 │ └─BioTools [fa51a905] log:
 │   ├─possible versions are: 1.0.0-1.1.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions: 1.0.0-1.1.0
 ├─restricted by compatibility requirements with FASTX [c2308a5c] to versions: 1.1.0-3.1.6 or uninstalled, leaving only versions: 1.1.0
 │ └─FASTX [c2308a5c] log:
 │   ├─possible versions are: 1.0.0-2.1.7 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions: 1.0.0-2.1.7
 └─restricted by compatibility requirements with GenomicAnnotations [4f8a0a0a] to versions: 2.0.0-3.1.6 — no versions left
   └─GenomicAnnotations [4f8a0a0a] log:
     ├─possible versions are: 0.1.0-0.3.8 or uninstalled
     └─restricted by compatibility requirements with BioFetch [f8217676] to versions: 0.2.0-0.3.8
       └─BioFetch [f8217676] log:
         ├─possible versions are: 0.1.0-0.2.1 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.2.1
```

## Steps to Reproduce (for bugs)

1. Start a Julia REPL in the environment detailed below
2. Enter Pkg mode, attempt to add BioTools

## Context
Wanted to install BioTools for the BLAST wrapper so I can automate some protein searches.

## Your Environment

- Package Version used: Whatever the most current one in the registry is, I think
- Julia Version used: 1.10.5
- Operating System and version (desktop or mobile): OS: Ubuntu 24.04.1 LTS on Windows 10 x86_64

 ```
 [f8217676] BioFetch v0.2.1
  [336ed68f] CSV v0.10.14
  [a93c6f00] DataFrames v1.7.0
  [0c46a032] DifferentialEquations v7.14.0
  [c2308a5c] FASTX v2.1.7
  [c3a54625] JET v0.9.9
⌃ [033835bb] JLD2 v0.5.3
⌃ [961ee093] ModelingToolkit v9.40.1
  [1dea7af3] OrdinaryDiffEq v6.89.0
  [91a5bcdd] Plots v1.40.8
  [1fd47b50] QuadGK v2.11.1
  [e5567a89] SBML v1.5.1
  [86080e66] SBMLToolkit v0.1.28
  [2913bbd2] StatsBase v0.34.3
  [d1185830] SymbolicUtils v3.7.1
  [8ba89e20] Distributed
  [37e2e46d] LinearAlgebra
```

**Comment by kescobo** [comment]
@hodgensc @jakobnissen Can you take a look at this package and let me know what you think? It's pretty bare-bones, but I think it's an MVP, and has pretty light-weight deps

https://github.com/BioJulia/NCBIBlast.jl

If there's interest, it might make sense to make some extensions for eg `DataFrames`, one or more of the JSON packages for different output formats, but for now that can be piped through files or `IO`-type objects.

**Comment by kescobo** [comment]
Please also take a look at https://github.com/BioJulia/NCBIBlast.jl/issues/1 if you're interested

**Comment by hodgensc** [comment]
Awesome! I took a look at it and I think it meets my needs! So far what you put together would be basically a clean replacement for what I've done already (which is run the queries manually from an input fasta, saving results to an output XML file that I processed with XML.jl, and manually copying the blast invocations to a text file). And all that's really missing then is some book-keeping around file paths, which would be my responsibility anyway.

If you ever did extend the functionality for the output formats, that would be neat, as there might be some growing pains for people with the current setup. For example, I'm not familiar with using IOBuffer objects, so I need a brush-up on those constructs if I want to use that functionality. For now though, I'm not sure it's necessary. Maybe if the new tool gets more uptake?

**Comment by kescobo** [comment]
`IOBuffer` is essentially what you get when you do something like `open(file_path)`. The trouble with just being able to pass a `String` is that julia doesn't have a filepath type, so paths are indistinguishable from a sequence string for example. 

I'll open an issue for this, and if you'd be interested, I could walk you through how I would handle this kind of thing. And if it works well, maybe you could make a PR :sweat_smile:
